exports.resources = [
    { type: 'book', name: 'The Grapes of Wrath', author: 'John Steinbeck', publish: '04-14-1939',
        content: `She seemed to know, to accept, to welcome her position, the citadel of the family, the strong place that could not be taken.` },
    { type: 'book', name: 'Encyclopedia of Networking and Telecommunications', author: 'Tom Sheldon', publish: '05-01-2001',
        content: `Directories contain elements that describe objects in the world, such as computers, folders, objects, managed resources, and even people. These element have names and, like the fields in a database, changing values.` },
    { type: 'movie', name: 'Mr. Smith Goes to Washington', author: 'Frank Capra', publish: '10-19-1939',
        content: `Your bill is ready. You take it over there and you introduce it. You get to your feet in the Senate and take a long breath and start spouting. But not too loud because a couple of the senators might want to sleep.` },
    { type: 'book', name: `Harry Potter and the Sorcerer's Stone`, author: 'J. K. Rowling', publish: '11-16-2001',
        content: `I can teach you how to bewitch the mind and ensnare the senses. I can teach you how to bottle fame, blew glory, and even put a stopper in death. However it seems some of you have come to class to not Pay attention.` },
    { type: 'book', name: 'The Poet X', author: 'Elezabeth Acevedo', publish: '03-06-2018',
        content: `Sometimes someone says something and their words are like the catch of a gas stove, the click, click while you're waiting for it to light up and flame big and blue...` },
    { type: 'song', name: 'Blue Dream', author: 'Jhene Aiko', publish: '05-07-2021',
        content: `My mind is open so wide since you came inside, I feel so alive. I was blinded, your smile shining behind those green eyes. The horizon so enticing, please say you'll be mine.` },
    { type: 'moive', name: 'Suits', author: 'Universal Studios Home Entertainment', publish: '06-23-2011',
        content: `What I think is if you can't figure out how to have a simple date with a woman who's already agreed to go out with you, then maybe you don't deserve to go out with her in the first place. How's that for advice?` },
    { type: 'book', name: 'The Psychology of Invention in the Mathematical Field', author: 'Jacques Hadamard', publish: '06-01-1954',
        content: `Here he was writing a formula the accuracy of which was certain, but whose origin in his brain and way of discovery he did not explain and we could not guess.` },
    { type: 'song', name: 'In My Life', author: 'The Beatles', publish: '12-03-1965',
        content: `These memories lose their meaning when I think of love as something new, though I know I'll never lose affection for people and things that went before. I know I'll often stop and think about them.` },
    { type: 'game', name: 'Starcraft', author: 'Blizzard Entertainment', publish: '01-31-1998',
        content: `The Swarms have crushed the meager human resistance and laid waste to nine of the thirteen Terran worlds. Shortly after the fall of the Terran capitol world of Tarsonis, the main Protoss fleet abandoned the Terran Sector. Now, effort continue on Tarsonis to weed out the remaining Protoss forces.` },
    { type: 'song', name: 'Because You Loved Me', author: 'Celine Dion', publish: '02-19-1996',
        content: `For all those times you stood by me, for all the truth that you made me see, for all the joy you brought to my life, for all the wrong that you made right.` },
    { type: 'song', name: 'Skeleton', author: 'Conditions', publish: '03-26-2013',
        content: `Like a stranger, I am on the outside looking in. I tore myself apart and I am left a skeleton. And it's been a long way down for me. It's been a long way down, but now I'm finally here. I will never understand.` },
    { type: 'movie', name: 'Pulp Fiction', author: 'Quentin Tarantino', publish: '10-14-1994',
        content: `Thing is Buth, right now you got ability. But painful as it may be, ability don't last. Now that's a hard fact of life, but it's a fact of life you're gonna have to get realistic about.` },
    { type: 'book', name: 'The Bloody Chamber', author: 'Angela Carter', publish: '1979',
        content: `I had the brief notion that his heart, pressed flat as a flower, crimson and thin as tissue paper, lay in this file. It was a very thin one.` },
    { type: 'book', name: `Astronomy: A beginer's Guilde to the Universe`, author: 'Eric Chaisson', publish: '1995',
        content: `Living in the solar system, we have the chance to study, at close range, perhaps the most common type of cosmic object - a star. Our Sun is a star, and a fairly average star at that, but with one unique feature: It is very close to us - some 300,000 times closer than the next nearest star, Alpha Centauri.` },
    { type: 'book', name: `Unlimited Memory`, author: 'Kevin Horsley', publish: '01-26-2014',
        content: `The great breakthrough in your life comes when you realize that you can learn anything you need to learn to accomplish any goal that you set for yourself.` },
    { type: 'book', name: `Being Mortal: Medicine and What Matters in the End`, author: 'Atul Gawande', publish: '10-07-2014',
        content: `We all require devotion to something more than ourselves for our lives to be endurable.` },
    { type: 'book', name: `Lazy Dog`, author: 'Carol Brown', publish: '05-08-2016',
        content: `The quick brown fox jumps over the lazy dog.` },
    { type: 'song', name: `Skyline Pigeon`, author: 'Elton John', publish: '08-01-1969',
        content: `Just let me wake up in the morning to the smell of new mown hay, to laugh and cry, to live and die in the brightness of my day. I want to hear the pealing bell of distant churches sing. But most of all please free me from this aching metal ring and open out this cage towards the sun.` },
    { type: 'movie', name: `The Unbearable Lightness of Being`, author: 'Philip Kaufman', publish: '02-05-1988',
        content: `I know I'm supposed to help you, but I can't. Instead of being your support I'm your weight. Life is very heavy to me, but it is so light to you.` },
    { type: 'song', name: `Infinite`, author: 'Andy Bane & Tyler Smyth', publish: '07-20-2017',
        content: `I'm the tallest of mountains. I am the roughest of waves. I'm the toughtest of terrors. I am the darkest of days. I'm the last one that's standing, don't try to stand in my way, 'cause I've been up against better, just take a look at my face.` },
    { type: 'book', name: `The Thermodynamics of Pizza`, author: 'Harold J. Marowitz', publish: '03-01-1991',
        content: `Convection also plays a minor role because of the relative thinness of the air layer and the presence of the upper cardboard hear shield. The insulation properties of teh cardboard plat a major role, since they serve to minimize the temperature gradient across the airspace.` },
    { type: 'song', name: `King of Anything`, author: 'Sara Bareilles', publish: '05-10-2010',
        content: `I'm not the one who's lost with no direction, but you'll never see me. You're so busy making masks with my name on them in all caps. You got the talking down, just not the listening.` },
    { type: 'book', name: `The Book of Illusions`, author: 'Paul Auster', publish: '07-13-2003',
        content: `If a tree falls in the forest and no one hears it fall, does it make sound or not? Hector had read a lot of books by then, he knew all the tricks and arguments of the philosophers. If someone makes a moive and no one see it, does the movie exist or not? That's how he justified what he did.` },
    { type: 'movie', name: `Searching for Bobby Fischer`, author: 'Steven Zaillian', publish: '09-12-1988',
        content: `Clear the lines of lint your head one at a time and the king will be left standing alone like a guy on a street corner. Here, I'll make it easier for you.` },
    { type: 'song', name: `Against All Odds`, author: 'Phil Collins', publish: '03-26-1984',
        content: `I wish I could just make you turn around and see me cry. There's so much I need to say to you, so many reasons why. You're the only one who really knew me at all.` },
    { type: 'book', name: `Me Before You`, author: 'Jojo Moyes', publish: '01-05-2012',
        content: `I hadn't realized that music could unlock things in you, could transport you to somewhere even the composter hadn't predicted. It left an imprint in the air around you, as if you carried its remnants with you when you went.` },
    { type: 'song', name: `Forever Young`, author: 'Bob Dylan', publish: '01-17-1974',
        content: `May your hands always be busy, may your feet always be swift. May you have a strong foundation when the winds of changes shift. May your heart always be joyful, may youer song always be sung, and may your stay forever young.` },
    { type: 'book', name: `The Power of Now`, author: 'Eckhart Tolle', publish: '1997',
        content: `Focus your attention on the Now and tell me what problem you have at this moment. I am not getting any answer because it is impossible to have a problem when your attention is fully in the Now.` },
    { type: 'song', name: `Green Eyes`, author: 'Coldplay', publish: '08-26-2002',
        content: `The green eyes, you're the one that I wanted to find and anyone who tried to deny you, must be out of their mind.` },
    { type: 'book', name: `Creativity Unlimited: Thinking Inside the Box for Business Innovation`, author: 'Micael Dahlen', publish: '07-13-2009',
        content: `The market ceiling can function in the same way as when you hit your head on the ceiling. You quickly crouch down and rub the sore spot. First-mover advantage, scale advantage and double jeopardy indicate that it can be quite painful to hit our head on the ceiling.` },
    { type: 'book', name: `The Omnivore's Dilemma: A Nature History of Four Meals`, author: 'Michael Pollan', publish: '2006',
        content: `At the very end of these food chains (which is to say, at the very beginning), I invariably found myself in almost exactly the same place: a farm field in the American Corn Belt.` },
    { type: 'movie', name: `Gattaca`, author: 'Andrew Niccol', publish: '10-24-1997',
        content: `For all my brave talk, I knew it was just that. No matter how much I trained or how much I studied, the best test score in the world wasn't gonna matter unless I had the blood test to go with it.` },
    { type: 'song', name: `Poems, Prayers, and Promises`, author: 'John Denver', publish: '04-06-1971',
        content: `How sweet it is to love someone, how right it is to care. How long it's been since yesterday, what about tomorrow, and what about our dreams and all the memories we share?` },
    { type: 'song', name: `My Favorite Things`, author: 'Oscar Hammerstein II', publish: '1959',
        content: `Girls in white dresses with blue satin sashes, snowflakes that stay on my nose and eyelashed, silver-white that melt into springs, these are a few of my favorite things.` },
    { type: 'book', name: `Nicomachean Ethic`, author: 'Aristotle', publish: '03-30-2004',
        content: `For as it is not one swallow or one find day that makes a spring, so it is not one day or a short time that makes a man blessed and happy.` },
    { type: 'song', name: `I'd Like to Teach The World To Sing`, author: 'New Seekers', publish: '11-01-1971',
        content: `I'd like to build the world a home and furnish it with love. Grow apple trees and honey bees and snow white turtle doves. I'd like to teach the world to sing in perfect harmony. I'd like to hold it in my arms and keep it company.` },
    { type: 'book', name: `House of Cards`, author: 'Beau Willimon', publish: '02-01-2013',
        content: `Power is lot like real estate. It's all about location, location, location. The closer you are to the source, the higher your property value.` },
    { type: 'song', name: `A Sort of Homecoming`, author: 'U2', publish: '1984',
        content: `And you know it's time to go, through the sleet and driving snow, across the fields of mourning, light in the distance. And you hunger for the time - time to heal, desire time, and your earth moves beneath your own dream landscape.` },
    { type: 'movie', name: `The Nightmare Before Christmas`, author: 'Tim Burton', publish: '10-15-1993',
        content: `I am the one hiding under your bed. Teeth ground sharp and eyes glowing red. I am the one hiding under your stairs. Fingers like snakes and spiders in my hair!` },
    { type: 'book', name: `Full Dark, No Stars`, author: 'Stephen King', publish: '11-09-2010',
        content: `He supposed that even in Hell, people got an accasional sip of water, if only so they could appreciate the full horror of unrequited thirst when it set in again.` },
    { type: 'movie', name: `The Perks of Being a Wallflower`, author: 'Stephen Chbosky', publish: '02-01-1999',
        content: `My doctor said we can't choose where we come from, but we can choose where we go from there. I know it's not all the answers, but it was enough to start putting these pieces together.` },
    { type: 'book', name: `Invisible Man`, author: 'Palph Ellison', publish: '1897',
        content: `I was never more hated than when I tried to be honest. Or when, even as just now I've tried to articulate exactly what I felt to be the truth. No one was satisfied.` },
];

exports.images = [
    { name: 'car', link: 'https://i.imgur.com/ldkblNL.png' },
    { name: 'keyboard', link: 'https://i.imgur.com/WfWCAw1.png' },
];