exports.resources = [
    { type: 'book', name: 'The Grapes of Wrath', author: 'John Steinbeck', publish: '04-14-1939',
        content: `She seemed to know, to accept, to welcome her position, the citadel of the family, the strong place that could not be taken.` },
    { type: 'book', name: 'Encyclopedia of Networking and Telecommunications', author: 'Tom Sheldon', publish: '05-01-2001',
        content: `Directories contain elements that describe objects in the world, such as computers, folders, objects, managed resources, and even people. These element have names and, like the fields in a database, changing values.` },
    { type: 'movie', name: 'Mr. Smith Goes to Washington', author: 'Frank Capra', publish: '10-19-1939',
        content: `Your bill is ready. You take it over there and you introduce it. You get to your feet in the Senate and take a long breath and start spouting. But not too loud because a couple of the senators might want to sleep.` },
    { type: 'book', name: `Harry Potter and the Sorcerer's Stone`, author: 'J. K. Rowling', publish: '11-16-2001',
        content: `I can teach you how to bewitch the mind and ensnare the senses. I can teach you how to bottle fame, blew glory, and even put a stopper in death. However it seems some of you have come to class to not Pay attention.` },
    { type: 'book', name: 'The Poet X', author: 'Elezabeth Acevedo', publish: '03-06-2018',
        content: `Sometimes someone says something and their words are like the catch of a gas stove, the click, click while you're waiting for it to light up and flame big and blue...` },
    { type: 'song', name: 'Blue Dream', author: 'Jhene Aiko', publish: '05-07-2021',
        content: `My mind is open so wide since you came inside, I feel so alive. I was blinded, your smile shining behind those green eyes. The horizon so enticing, please say you'll be mine.` },
    { type: 'moive', name: 'Suits', author: 'Universal Studios Home Entertainment', publish: '06-23-2011',
        content: `What I think is if you can't figure out how to have a simple date with a woman who's already agreed to go out with you, then maybe you don't deserve to go out with her in the first place. How's that for advice?` },
    { type: 'book', name: 'The Psychology of Invention in the Mathematical Field', author: 'Jacques Hadamard', publish: '06-01-1954',
        content: `Here he was writing a formula the accuracy of which was certain, but whose origin in his brain and way of discovery he did not explain and we could not guess.` },
    { type: 'song', name: 'In My Life', author: 'The Beatles', publish: '12-03-1965',
        content: `These memories lose their meaning when I think of love as something new, though I know I'll never lose affection for people and things that went before. I know I'll often stop and think about them.` },
    { type: 'game', name: 'Starcraft', author: 'Blizzard Entertainment', publish: '01-31-1998',
        content: `The Swarms have crushed the meager human resistance and laid waste to nine of the thirteen Terran worlds. Shortly after the fall of the Terran capitol world of Tarsonis, the main Protoss fleet abandoned the Terran Sector. Now, effort continue on Tarsonis to weed out the remaining Protoss forces.` },
    { type: 'song', name: 'Because You Loved Me', author: 'Celine Dion', publish: '02-19-1996',
        content: `For all those times you stood by me, for all the truth that you made me see, for all the joy you brought to my life, for all the wrong that you made right.` },
    { type: 'song', name: 'Skeleton', author: 'Conditions', publish: '03-26-2013',
        content: `Like a stranger, I am on the outside looking in. I tore myself apart and I am left a skeleton. And it's been a long way down for me. It's been a long way down, but now I'm finally here. I will never understand.` },
    { type: 'movie', name: 'Pulp Fiction', author: 'Quentin Tarantino', publish: '10-14-1994',
        content: `Thing is Buth, right now you got ability. But painful as it may be, ability don't last. Now that's a hard fact of life, but it's a fact of life you're gonna have to get realistic about.` },
    { type: 'book', name: 'The Bloody Chamber', author: 'Angela Carter', publish: '1979',
        content: `I had the brief notion that his heart, pressed flat as a flower, crimson and thin as tissue paper, lay in this file. It was a very thin one.` },
    { type: 'book', name: `Astronomy: A beginer's Guilde to the Universe`, author: '', publish: '1995',
        content: `Living in the solar system, we have the chance to study, at close range, perhaps the most common type of cosmic object - a star. Our Sun is a star, and a fairly average star at that, but with one unique feature: It is very close to us - some 300,000 times closer than the next nearest star, Alpha Centauri.` },
];

exports.history = [
    { speed: 45, time: '01-18-2021', source: "61e9ecaf477e98d3d7c8ee3f" },
    { speed: 42, time: '01-28-2021', source: "61e9ecaf477e98d3d7c8ee42" },
    { speed: 38, time: '01-17-2021', source: "61e9ecaf477e98d3d7c8ee44" },
    { speed: 57, time: '01-20-2021', source: "61e9ecaf477e98d3d7c8ee3f" },
    { speed: 60, time: '01-21-2021', source: "61e9ecaf477e98d3d7c8ee46" },
    { speed: 53, time: '01-18-2021', source: "61e9ecaf477e98d3d7c8ee46" },
];